[WARN ][20171201 10:48:07,694][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 10:48:12,703][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering queue immediate_queue: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering queue immediate_queue: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverQueues(AutorecoveringConnection.java:632)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:583)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:952)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedQueue.recover(RecordedQueue.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverQueues(AutorecoveringConnection.java:608)
	... 8 more
[WARN ][20171201 10:48:37,518][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 10:49:12,556][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 10:50:09,927][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 11:11:42,663][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 11:17:44,135][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 11:17:49,141][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 11:18:14,519][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 11:18:19,526][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 11:18:57,730][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 11:19:02,736][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 11:19:20,580][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 11:19:37,416][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 11:23:34,369][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 11:23:39,376][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 14:12:42,999][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 14:12:48,005][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 14:23:44,814][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 14:33:05,851][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 14:33:10,857][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delay_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delay_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 14:35:39,279][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 14:35:44,285][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 14:38:48,668][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 14:40:07,539][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 14:40:41,900][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[WARN ][20171201 15:21:05,865][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 15:21:10,871][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[ERROR][20171201 15:24:05,654][ForgivingExceptionHandler:124] An unexpected connection driver error occured
java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
	at java.lang.Thread.run(Thread.java:748)
[ERROR][20171201 15:24:05,659][ForgivingExceptionHandler:124] An unexpected connection driver error occured
java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
	at java.lang.Thread.run(Thread.java:748)
[ERROR][20171201 15:25:32,486][ForgivingExceptionHandler:124] An unexpected connection driver error occured
java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
	at java.lang.Thread.run(Thread.java:748)
[ERROR][20171201 15:25:32,490][ForgivingExceptionHandler:124] An unexpected connection driver error occured
java.net.SocketException: socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
	at java.lang.Thread.run(Thread.java:748)
[ERROR][20171201 15:38:39,757][ForgivingExceptionHandler:124] An unexpected connection driver error occured
java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
	at java.lang.Thread.run(Thread.java:748)
[ERROR][20171201 15:38:39,759][ForgivingExceptionHandler:124] An unexpected connection driver error occured
java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
	at java.lang.Thread.run(Thread.java:748)
[WARN ][20171201 15:38:54,790][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 15:38:59,797][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 15:39:35,078][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 15:39:40,085][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 15:54:42,490][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 15:54:47,496][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
[WARN ][20171201 15:55:24,414][ForgivingExceptionHandler:120] An unexpected connection driver error occured (Exception message: Connection reset)
[ERROR][20171201 15:55:29,420][ForgivingExceptionHandler:124] Caught an exception when recovering topology Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering exchange delayed_exchange: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:597)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:582)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:506)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.recoveryCanBegin(AutorecoveringConnection.java:435)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:252)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:136)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:767)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:709)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:53)
	at com.rabbitmq.client.impl.recovery.RecordedExchange.recover(RecordedExchange.java:35)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverExchanges(AutorecoveringConnection.java:593)
	... 8 more
